# -*- coding: utf-8 -*-
"""NLP_Lab_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uM7uYV_SWajPe1VeOXDMOgGl7TDmbcQ-
"""

import re

def clean_text(text):

    # Remove URLs
    text = re.sub(r'http\S+|www\.\S+', '', text)

    # Remove email addresses
    text = re.sub(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b', '', text)

    # Remove special characters (except spaces)
    text = re.sub(r'[^A-Za-z0-9\s]', '', text)

    # Normalize whitespace
    text = re.sub(r'\s+', ' ', text).strip()

    return text

# Example Usage
sample_text = """
Hello! You can reach out to us, contact@mysite.com for any inquiries.
Check our website: https://www.mysite.com/products or follow us on social media at http://facebook.com/mysite!
Limited-time offers are available for $19.99 only. Don't miss out - register at www.mysite.com/signup now!
For partnership queries, email us partners@business.com)
"""

cleaned_text = clean_text(sample_text)
print("Cleaned Text:")
print(cleaned_text)